### ISSUE TITLE
[Bug] weird displacement bug when clicking any element on the panes

### ISSUE THREAD

**Issue by albertoloscerritos** [HandaArchitect/obsidian-banner-snippet#13]
Hi. Great work as always. I think I found a weird bug when using the banner snippet. If I select a banner for a page, and click on anything on the left pane (e.g. search button, folders, bookmarks button, etc) the content of the note moves, and I need to re-click on the note for the content to appear in the correct position. Please check the following gif...

![bug_banner](https://github.com/user-attachments/assets/a3c37af7-1f48-4c2e-a2ae-5da04a095bd7)

I am using windows 11 and obsidian 1.7.3 sandbox
Thanks

**Comment by HandaArchitect** [comment]
I have figured out what was causing this. Please check v1.3.2 if the issues you have mentioned persist.

**Comment by albertoloscerritos** [comment]
Hi. Thanks for the update. I tried it and it definitely fixed the issue. I will let you know if anything changes. 
Awesome snippet 😎
