### ISSUE TITLE
[BUG]: Properties show on top of banner when note is not in focus.

### ISSUE THREAD

**Issue by DudeThatsErin** [HandaArchitect/obsidian-banner-snippet#16]
I am on Obsidian 1.7.5 on Windows 11.

I have a GIF of this happening so you can see what I am talking about:
https://github.com/user-attachments/assets/af099171-99d5-4b93-ad3b-5e9865be0a30

You can see in the gif I disable all of my other snippets other than this one and it still happens so it isn't a snippet issue.

I'm good with temporarily disabling the inline properties but I am ultimately wanting to be able to keep them as an option.

**Comment by HandaArchitect** [comment]
Can you please include the theme you are using?

Often, it is the theme that breaks the snippet due to some property that I would need to override.

**Comment by DudeThatsErin** [comment]
Default theme with my snippets.

Sent from my iPad

On Nov 4, 2024, at 9:22 PM, HandaArchitect ***@***.***> wrote:

﻿

Can you please include the theme you are using?

Often, it is the theme that breaks the snippet due to some property that I would need to override.

**Comment by DudeThatsErin** [comment]
Just wanted to update that it is happening now with limited snippets on the default theme. Even with all snippets off it is happening on the default theme on v1.7.7 and v1.7.6

**Comment by DudeThatsErin** [comment]
Solved. I re-downloaded the `.css` file and it is all fixed. I must have made changes to the CSS file that caused this.

Thanks for following up! Love the snippet!
