### ISSUE TITLE
Bug, can't remove the shadow in the back of the title

### ISSUE THREAD

**Issue by albertoloscerritos** [HandaArchitect/obsidian-banner-snippet#2]
Hi, first of all thank for the great work. I really appreciate the snippet you created. 
I think there is a problem, I can't seem to be able to remove the white shadow box that is behind the title
![image](https://github.com/HandaArchitect/obsidian-banner-snippet/assets/16707033/a1cb2076-d312-43ec-8788-f75e8f188db1)
Do you know if this is possible. Thanks.

**Comment by HandaArchitect** [comment]
Thank you. Issue fixed in next release v1.2.1
