### ISSUE TITLE
Bug, emoji in half

### ISSUE THREAD

**Issue by albertoloscerritos** [HandaArchitect/obsidian-banner-snippet#3]
Hi, me again. I think there is another bug. I was using the snippet and changed the banner to faded, and then back to normal. And now the emoji is in half
![image](https://github.com/HandaArchitect/obsidian-banner-snippet/assets/16707033/944868e0-51a4-4d23-b8c3-59d78d55a758)
Even if I select another emoji. I can't seem to fix it. I am using the default theme and obsidian v 1.6.1.
Thanks.

**Comment by HandaArchitect** [comment]
I've adjusted a setting to hopefully fix this. Please let me know if this resolves for you in v1.2.1. Releasing soon.

**Comment by HandaArchitect** [comment]
I've just made the latest release https://github.com/HandaArchitect/obsidian-banner-snippet/releases/tag/v1.2.1

**Comment by albertoloscerritos** [comment]
Hi. Thanks for answering. Just tried the new release but I think it is not working anymore.
Here is a picture of how my banners look in my usual vault.
![image](https://github.com/HandaArchitect/obsidian-banner-snippet/assets/16707033/1ca2d54a-7ae9-4fd3-b1bc-e03ed761108c)
![image](https://github.com/HandaArchitect/obsidian-banner-snippet/assets/16707033/093ecdbe-f157-4fc1-ac0d-e3d2710a4479)
![image](https://github.com/HandaArchitect/obsidian-banner-snippet/assets/16707033/0ee9a406-ae2c-4849-b0e8-dfed8d7804d0)

 And here is how it looks in a fresh new vault 
![image](https://github.com/HandaArchitect/obsidian-banner-snippet/assets/16707033/f45456c8-9913-4e2c-bdd8-a9f7779accf7)
I am using windows 11 obsidian 1.6.1
Am I doing something wrong? Thanks.

**Comment by albertoloscerritos** [comment]
Edit, just double checked and it only seems to happen in editing mode (it wasn't the case before):


![banner_bug](https://github.com/HandaArchitect/obsidian-banner-snippet/assets/16707033/12df9dca-4b5c-4dfd-b11f-e66379a96e83)

**Comment by HandaArchitect** [comment]
Sorry about that. It looks like v1.2.1 is broke. I've just tested v1.2.2 and it looks to be working as expected. Thank you for reporting the bugs. Releasing v1.2.2 now.

**Comment by albertoloscerritos** [comment]
Thanks. It seems to work properly. I will keep using it and report other bugs if I find any.
