### ISSUE TITLE
[Feature Request] Option to change the shown portion of the image

### ISSUE THREAD

**Issue by albertoloscerritos** [HandaArchitect/obsidian-banner-snippet#4]
Hi, I think it would be a great addition to be able to change the portion of the image that is shown in the banner. Here is a picture to visualize what I mean:
![image](https://github.com/HandaArchitect/obsidian-banner-snippet/assets/16707033/263a12ef-2160-4695-84c6-16f7ec2fc302)

Maybe one way to do this would be by adding a cssclasses property. Like, typing 0 would mean to show from the beginning of the image to the 250 px (in cases that is the selected banner height). Typing 300 would show from the 300 px  to the 550px. Hopefully you like the idea. Thanks.

**Comment by mrazarny** [comment]
+1 

ya i also wanna this

**Comment by HandaArchitect** [comment]
This can be done using percentages. I'll look into it.

**Comment by albertoloscerritos** [comment]
Awesome. Thanks :)

**Comment by HandaArchitect** [comment]
@mrazarny @albertoloscerritos 
resolved in v1.3.0

**Comment by mrazarny** [comment]
ty buddy for good work

**Comment by albertoloscerritos** [comment]
Thanks for the awesome job :)
