### ISSUE TITLE
{Feature Request} ability to read the yaml

### ISSUE THREAD

**Issue by mrazarny** [HandaArchitect/obsidian-banner-snippet#5]
if its possible to make the snippet read data from the yaml _'properties'_ section instead of the regular embed method for e.g:

---
cssclasses: banner 
banner: "[[x.gif|banner]]"
---

like how banner plugin handle the banners

**Comment by HandaArchitect** [comment]
Sorry, this is not possible as the snippet uses CSS/SCSS which is limited in what it can do. As the properties section does not actually show an image, there is no image element that I can manipulate and transform into a banner on the page. If you need to process multiple notes and add the banner, you could use a script that takes the banner property of a note and changes it into an image attachment.
