### ISSUE TITLE
banner icons doesnt show up in live preview

### ISSUE THREAD

**Issue by ChubbyChipmunk77** [HandaArchitect/obsidian-banner-snippet#6]
i have a animated gif as banner which works pretty well , but whenever i try to add a banner icon , the icon doesnt shows up in live preview mode and only shows up in reading mode , pls resolve this if possible or tell me any possible workaround or a css snippet to help me out ... here is the sample example of the issue in my vault 

with live preview mode on in editing view 
<img width="955" alt="image" src="https://github.com/HandaArchitect/obsidian-banner-snippet/assets/172578519/48bddce6-b096-4ab0-91ea-0c44ff4d5ddd">

in reading mode 
<img width="886" alt="image" src="https://github.com/HandaArchitect/obsidian-banner-snippet/assets/172578519/a4519ea7-d1d1-4dd8-ad44-6d414be9cb08">

as for my theme , its a beefy riced up blue topaz theme with a few css snipets , i do have a ton of plugins too so yeah , thought of sharing these info as it might help find the issue somehow ?

**Comment by HandaArchitect** [comment]
I'll try to replicate that issue and get back to you on that one when I find time.

**Comment by HandaArchitect** [comment]
The blue topaz theme made some changes that caused the banner icon to disappear. This issue has been fixed and will be released in the next release. Hoping to release it in the next few days.

**Comment by HandaArchitect** [comment]
resolved in v1.3.0
