### ISSUE TITLE
Can you help with position feature?

### ISSUE THREAD

**Issue by mooshiraine** [HandaArchitect/obsidian-banner-snippet#9]
![Screenshot_5](https://github.com/user-attachments/assets/f0c06e46-1c47-45ba-8723-449df2eb7c6e)

Hi, am I doing something wrong? Banner is just don't show if I put -y50

**Comment by HandaArchitect** [comment]
Hi @mooshiraine , you need to add "banner" and "banner-y50". However, adding y50 should not be needed as that is the defaul5 y-value.

**Comment by mooshiraine** [comment]
Thanks, it works perfectly! <3
